#game settings
RES = WIDTH, HEIGHT = 1600, 900
FPS = 144

#car settings
CAR_IMAGE = 'images/car.png'
CAR_WIDTH = 25
CAR_HEIGHT = 50
CAR_POSITION = WIDTH / 2, HEIGHT / 2
MAX_SPEED = 2
ACCELERATION = MAX_SPEED / 200
MAX_ROTATION_SPEED = MAX_SPEED / 1.5
FRICTION = MAX_SPEED / 100
BRAKE_SPEED = 1.01

#road settings
GRASS_IMAGE = 'images/grass.png'

