#game settings
RES = WIDTH, HEIGHT = 1600, 900
FPS = 144

#road settings
TILE_SIZE = 100
TILE_CENTER = TILE_SIZE / 2
GRID_IMAGE = 'images/grid.png'
GRASS_IMAGE = 'images/grass.png'
FINISH_IMAGE = 'images/finish.png'
STRAIGHT_IMAGE = 'images/straight.png'
CORNER_IMAGE = 'images/corner.png'
CAR_AMOUNT = 1

#car settings
CAR_IMAGE = 'images/car.png'
CAR_WIDTH = TILE_SIZE / 6
CAR_HEIGHT = CAR_WIDTH * 2
MAX_SPEED = 2
ACCELERATION = MAX_SPEED / 150
ROTATION_SPEED = 1.2
CORNERING_SPEED = ROTATION_SPEED * 10
FRICTION = MAX_SPEED / 150
BRAKE_SPEED = 1.01

#raycast  settings
NUM_OF_RAYS = 1
RAY_SPREAD = 0
HALF_SPREAD = RAY_SPREAD / 2
RAY_GAP = RAY_SPREAD / NUM_OF_RAYS if NUM_OF_RAYS == 1 else NUM_OF_RAYS - 1



